# Generated by Django 3.1.6 on 2021-02-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210205_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quesion',
            new_name='question',
        ),
    ]
