# Generated by Django 3.1.6 on 2021-02-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
